### ISSUE TITLE
Are these docs outdated?

### ISSUE THREAD

**Issue by MikeModder** [boxbilling/docs#2]
I'm looking through the docs (https://docs.boxbilling.com) and I see some spelling errors and not much information regarding some of the API calls. This is semi-related to boxbilling/boxbilling#515. I also see that the latest commit is from a few years ago, and a PR that's been untouched.

I was wondering if these docs have been replaced with something else, and why the have seemingly been neglected.

**Comment by Eiskaltereistee** [comment]
Hi,

I think there is no active development on BoxBilling, also the Documentation is not longer "up-to-date". It just have the state since some years.

But @TuxMay is a bit active here on github - If you pull request the changes he would review and accept them, I think.

**Comment by TuxMay** [comment]
@MikeModder The BoxBilling docs are meant as a guide & are handwritten by our developers (English is not there primary language, hence the spelling mistakes). Regarding API calls, unless you are a developer with experience with API calls, then you may not understand them properly as we do have queries on API queries all the time from customers who unfortunately do not know how to use API & want it to be easy copy & paste..

@Eiskaltereistee Correct, I am active from time to time, I do not just pull any request, I do manually check the pull request & ensure that it works correctly.
