### ISSUE TITLE
Read the Docs not rebuilding from this repo

### ISSUE THREAD

**Issue by S4-Hosting** [boxbilling/docs#4]
According to the RtD documentation the docs should rebuild almost instantly when this repo is updated. 

This isn't happening, the repo was updated several hours ago and the docs haven't rebuilt. 

The builds page at RtD shows that it hasn't even tried to rebuild the docs since this change and that the last attempts to rebuilt before that (3 years ago) all failed. See: https://readthedocs.org/projects/boxbilling/builds/?page=1

Can we check that they are linked correctly please.

**Comment by S4-Hosting** [comment]
I think the only person who could easily solve this issue would be someone who has the ability to log into the Read the Docs account and also the right to re-authorize RtD to pull from the repo. @fordnox  would that be you?

**Comment by fordnox** [comment]
![Screenshot 2020-10-10 at 14 37 10](https://user-images.githubusercontent.com/398619/95654068-17af3600-0b06-11eb-9d7b-2ee55b9d3dbf.png)

**Comment by fordnox** [comment]
Build passing
